### ISSUE TITLE
How to modify texture

### ISSUE THREAD

**Issue by KerrahChan** [fbxiang/NeuTex#4]
I can't find the code where the texture modification is injected to the network, could you please give some guidance?

**Comment by fbxiang** [comment]
The code for texture modification is not provided but it is quite straightforward.
How the network operates is the following:
for each point in ray marching, 1. pass it through the UV and density network to find UV and density, 2. pass UV through the texture network to find color.
The texture editing adds the next step 3. take the UV and read a modified texture to get color2 , 4. compose the 2 colors (e.g. multiply, add, etc, etc).
To know where to put the edits on the texture, the best way is to take one output cube map, import it into a 3D software to texture a sphere, and start texture painting on  the sphere, but in the paper I really just drew on the 2D cube map.

**Comment by KerrahChan** [comment]
Thanks. I understand that now.
One more question for that. For a specific camera pose, are all the sampling points mapped onto the texture space sphere surface uniformly, which means some meaningless points (like some points in the empty space) will appear when we pass UV through the texture network?

**Comment by fbxiang** [comment]
Yes, your understanding is correct. Those points will have density very close to 0 so it does not matter what values they take.
